name: publish website with xmake on windows
on:
  push:
    tags: '*'

jobs:
  build:
    runs-on: windows-latest
    if: always()
    env:
      # Force xmake to a specific folder (for cache)
      XMAKE_GLOBALDIR: "${{ github.workspace }}\\.xmake-global"
      DOXYGEN_VERSION: 1.9.5
    steps:
      - uses: xmake-io/github-action-setup-xmake@v1
        with:
          xmake-version: v2.8.3
      - name: update repo
        run: |
          xrepo update-repo
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - uses: actions/checkout@v4
        with:
          ref: gh-pages
          path: build/website
          fetch-depth: 1
      - name: cache packages from xrepo
        uses: actions/cache@v2
        with:
          path: |
            ${{ env.XMAKE_GLOBALDIR }}/.xmake/packages
          key: ${{ runner.os }}-xrepo-qt-${{ hashFiles('scripts/xmake/packages.lua') }}
      - name: cache xmake
        uses: actions/cache@v2
        with:
          path: |
            ${{ github.workspace }}/.xmake/**/cache
            ${{ github.workspace }}/build/.build_cache
            ${{ github.workspace }}/build/.deps
            ${{ github.workspace }}/build/.gens
            ${{ github.workspace }}/build/.objs
          key: ${{ runner.os }}-xmake-build-${{ hashFiles('**/xmake.lua') }}
      - name: Cache doxygen
        id: cache
        uses: actions/cache@v2
        with:
          path: doxygen
          key: ${{ runner.os }}-doxygen-${{ env.DOXYGEN_VERSION }}

      - name: "Setup doxygen"
        if:  steps.cache.outputs.cache-hit != 'true'
        run: |
          mkdir doxygen
          cd doxygen
          $release = "${{env.DOXYGEN_VERSION}}".replace(".", "_")
          Invoke-WebRequest -Uri "https://github.com/doxygen/doxygen/releases/download/Release_$release/doxygen-${{env.DOXYGEN_VERSION}}.windows.x64.bin.zip" -OutFile doxygen.zip
          Expand-Archive -Path doxygen.zip -DestinationPath $PWD.Path
          echo $PWD.Path | Out-File -Append -FilePath $env:GITHUB_PATH -Encoding utf8
          rm doxygen.zip
      - name: install by xmake
        run: |
          xmake config --yes --mode=release --generate-repository=y
          xmake build --jobs=2
          xmake install installer
          xmake doxygen --yes --outputdir=build/website/api
      
      - name: Release installer
        uses: softprops/action-gh-release@v1
        with:
          body_path: ${{ github.workspace }}/CHANGELOG.md
          draft: ${{ startsWith(github.ref, 'refs/tags/nightly') }}
          fail_on_unmatched_files: true
          files: |
            build/website/ProMidiEdit.exe
      - name: Publish website
        run: |
          cd build/website
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "Generate Website for ${{ github.ref }}"
          git push
